SELECT
    ARTICULOS.CODARTICULO AS CODARTICULO,
    REFPROVEEDOR,
    DESCRIPCION,
    TIPOIMPUESTO,
    SECCION,
    FAMILIA,
    SUBFAMILIA,
    UNIDADMEDIDA,
    PESO_CRUDO,
    PESO_COCIDO,
    JERARQUIA_PRODUCCION
FROM
    ARTICULOS
    LEFT JOIN ARTICULOSCAMPOSLIBRES
ON
    ARTICULOS.CODARTICULO=ARTICULOSCAMPOSLIBRES.CODARTICULO